# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'testPod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Mediatom
  pod 'CMediaSDK', '2.7.8'

  # 以下按需导入
  
  # 穿山甲
  pod 'CMediaSDK/SFAdCsjAdapter'
  
  # 优量汇
  pod 'CMediaSDK/SFAdGdtAdapter'
  
  # 快手联盟
  pod 'CMediaSDK/SFAdKsAdapter'
  
  # 百度
  # pod 'CMediaSDK/SFAdBaiduAdapter'
  
  # 京准通
  # pod 'CMediaSDK/SFAdJztAdapter'
  
  # 汇盈
  # pod 'CMediaSDK/SFAdHrAdapter'
  
  # 天目
  # pod 'CMediaSDK/SFAdTmAdapter'
  
  # 章鱼
  # pod 'CMediaSDK/SFAdZyAdapter'
  
  # 优推
  # pod 'CMediaSDK/SFAdYtAdapter'
  
  # 科大讯飞
  # pod 'CMediaSDK/SFAdKdxfAdapter'
  
  # Beizi
  # pod 'CMediaSDK/SFAdBeiziAdapter'
  
  # Meishu
  # pod 'CMediaSDK/SFAdMsAdapter'
  
  # Sigmob
  # pod 'CMediaSDK/SFAdSigmobAdapter'
  
  # Mintegral
  # pod 'CMediaSDK/SFAdMtgAdapter'
  
  # Pangle
  # pod 'CMediaSDK/SFAdPangleAdapter'
  
  # AdMob
  # pod 'CMediaSDK/SFAdMobAdapter'
  
  # Meta
  # pod 'CMediaSDK/SFAdMetaAdapter'
  
  # Vungle
  # pod 'CMediaSDK/SFAdVungleAdapter'
  
  # Tanx
  # pod 'CMediaSDK/SFAdTbAdapter'
  
  # UnityAds
  # pod 'CMediaSDK/SFAdUnityAdapter'
  
  # Applovin
  # pod 'CMediaSDK/SFAdApplovinAdapter'

  # Ironsource
  # pod 'CMediaSDK/SFAdIronsourceAdapter'

  # Inmobi
  # pod 'CMediaSDK/SFAdInmobiAdapter'

  # Bigo
  # pod 'CMediaSDK/SFAdBigoAdapter'
  
  # TopOn
  # pod 'CMediaSDK/SFAdTnAdapter'
  
  # TradPlus
  # pod 'CMediaSDK/SFAdTpAdapter'
 

end
post_install do |installer|
  installer.aggregate_targets.each do |target|
    target.xcconfigs.each do |variant, xcconfig|
      xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
      IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
    end
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
        xcconfig_path = config.base_configuration_reference.real_path
        IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
      end
    end
  end
end
