# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ADDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # CMediaSDK主包
  pod 'CMediaSDK'

  # 以下按需导入
  
  # 穿山甲
  pod 'CMediaSDK/SFAdCsjAdapter'
  
  # 优量汇
  pod 'CMediaSDK/SFAdGdtAdapter'
  
  # 快手联盟
  pod 'CMediaSDK/SFAdKsAdapter'
  
  # 百青藤
  #pod 'CMediaSDK/SFAdBaiduAdapter'
  
  # 京准通
  pod 'CMediaSDK/SFAdJztAdapter'

end
